spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tsuchiya-question
    username: postgres
    password: postgres

    
    jmx:
      enabled: false
